#!/usr/bin/env bash
# Configure your domain zone so that the subdomain www points to your
# load balancer IP (lb-01)

if [ "$2" == "" ]; then
    list=("www" "lb-01" "web-01" "web-02")
    for subdomain in "${list[@]}"
    do
        cmd="$(dig "$subdomain.$1" | grep -A1 'ANSWER SECTION:' | awk 'NF>0 && $5 != "" {print $5}')"
        echo "The subdomain $subdomain is a A record and points to $cmd"
    done
else
    val="$(dig "$2.$1" | grep -A1 'ANSWER SECTION:' | awk 'NF>0 && $5 != "" {print $5}')"
    echo "The subdomain $2 is a A record and points to $val"
fi
