#!/usr/bin/env bash
# Install nginx web server

# update before installing
apt-get -y update

# Install Nginx
apt-get install -y nginx

# Allow uncomplicated Firewall
ufw allow 'Nginx HTTP'

# Create a default page that returns "Hello World!"
echo "Hello World!" > /var/www/html/index.nginx-debian.html

# Restart Nginx using service command
service nginx start
