#!/usr/bin/env bash
# Redirection

# update before installing
# apt-get -y update

# # Install Nginx
# apt-get install -y nginx

# # Allow uncomplicated Firewall
# sudo ufw allow 'Nginx HTTP'

# Create a default page that returns "Hello World!"
# echo "Hello World!" > /var/www/html/index.html


# Redirection
config="server {
            listen 80 default_server;
            listen [::]:80 default_server;

            root /var/www/html;
            index index.html index.htm index.nginx-debian.html;

            server_name _;

            location / {
                try_files \$uri \$uri/ =404;
            }

            location /redirect_me {
                return 301 https://www.rashisky.com\n;
            }
        }"

echo "$config" > /etc/nginx/sites-available/default

# Restart Nginx using service command
# check if nginx is already started or not
if [ $(pgrep -c nginx) -le 0 ]
then
	service nginx start
else
	service nginx restart
fi
