#!/usr/bin/env bash
# Customize Not found page 404


# update before installing
apt-get update

# Install Nginx
apt-get install -y nginx

# Create a default page that returns "Hello World!"
echo "Hello World!" > /var/www/html/index.html
echo -e "Ceci n'est pas une page\n" > /var/www/html/404.html

# Redirection
config="server {
            listen 80 default_server;
            listen [::]:80 default_server;

            root /var/www/html;
            index index.html index.htm index.nginx-debian.html;

            server_name _;

            location / {
                try_files \$uri \$uri/ =404;
            }

            location /redirect_me {
                return 301 \"https://www.rashisky.com\";
            }

            error_page 404 /404.html;

            location = /404.html {
                internal;
            }
        }"

echo -e "$config" > /etc/nginx/sites-available/default

# Restart Nginx using service command
# check if nginx is already started or not
if [ "$(pgrep -c nginx)" -le 0 ]
then
	service nginx start
else
	service nginx restart
fi

# NOTE: There is a slight difference btw the two below
# location = /404.html {
#                 internal;
#             }
# and
# location /404.html {
#                 root /var/www/html;
#             }
