#!/usr/bin/env bash
# Bash Script that pings an IP address passed as an argument
# Requirement
# Accepts a string as an argument, else displays file_name if no arg given
# Ping the IP 5 times

if [ "$#" -eq 0 ];
then
    echo "Usage: $0 {IP_ADDRESS}"
else
    ping -c 5 "$1"
fi
