#!/usr/bin/env bash
# Script that displays the content of the file /etc/passwd, using
# "while" loop + IFS.
# Format: The user USERNAME is part of the GROUP_ID gang, lives in
# HOME_DIRECTORY and rides COMMAND/SHELL. USER ID's place is protected
# by the passcode PASSWORD, more info about the user here: USER ID INFO

while IFS=":" read -r v1 v2 v3 v4 v5 v6 v7
do
    echo "The user "$v1" is part of the "$v4" gang, lives in "$v6" and \
rides "$v7". "$v3"'s place is protected by the passcode "$v2", \
more info about the user here: "$v5""
done < /etc/passwd
