#!/usr/bin/env bash
# Prints using while loop and conditional statement
k=1
while [ "$k" -le 10 ];
do
    if [[ "$k" = 4 ]]
    then
        echo "bad luck"
    elif [ "$k" = 8 ]
    then
        echo "good luck"
    else
        echo "Best School"
    fi
    ((k++))
done
