#!/usr/bin/env bash
# prints using case statement
k=1
while [ "$k" -le 20 ];
do
    case "$k" in
        4)
            echo "bad luck from China"
            ;;
        9)
            echo "bad luck from Japan"
            ;;
        17)
            echo "bad luck from Italy"
            ;;
        *)
            echo "$k"
            ;;
    esac
    ((k += 1))
done
