#!/usr/bin/env bash
# Run Nginx web server using the user "nginx" and on port 8080
sed -i 's/user.*/user nginx;/' /etc/nginx/nginx.conf
sed -i 's/80/8080/g' /etc/nginx/sites-available/default
sudo -u nginx systemctl start nginx
